[package]
name = "crossref"
version = "0.1.0"
authors = ["Richard Dodd <richard.o.dodd@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
url = "1.7.2"
